### ISSUE TITLE
Add a filter for schema:license

### ISSUE THREAD

**Issue by acka47** [philbarker/LRMISearch#1]
Hello @philbarker, thanks for setting this up. It would be nice to also have a filter for all resources that have `schema:license` on them to approximately filter for openly licensed educational resources. I will try to make a PR for this.

**Comment by philbarker** [comment]
Cool, thanks @acka47 
Seems to work, and is now in the demo. The first result I see has a license url 	https://www.landportal.org/voc/licences/all-rights-reserved so not remotely open.

Not for this search engine, but if you do fancy a CSE for open licenses then filters like 
```
   <Rewrite>more:p:CreativeWork-license:https://creativecommons.org/licenses/by/2.0/
      OR more:p:CreativeWork-license:CC:BY
   </Rewrite>
```
should get you them (I haven't tested it). But my guess is it will be a long list of variations to get them all.

**Comment by acka47** [comment]
Thanks for merging this and thanks for the hint on how to filter for open licenses. Your are right, that this does not say much about open resources. However, it is interesting to see how the `license` property is sometimes (mis)used. Closing.
